"""Markdown report: a human-readable summary meant for reading in a
terminal, pasting into a GitHub PR/issue, or a quick look without
opening the full JSON."""

from __future__ import annotations

from pathlib import Path

from elenk.core.models import ScanResult, Severity

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
    Severity.UNKNOWN: "⚪",
}

_MAX_DESCRIPTION_CHARS = 140
_MAX_DESCRIPTION_HARD_CAP = 200


def _shorten(text: str, limit: int = _MAX_DESCRIPTION_CHARS, hard_cap: int = _MAX_DESCRIPTION_HARD_CAP) -> str:
    """Keeps only a short teaser of a finding's description: the first
    sentence when there is one nearby, otherwise a clean cut at a word
    boundary — never a hard chop mid-word, which reads like the text
    got cut off by accident rather than shortened on purpose."""
    text = " ".join(text.split())
    if len(text) <= limit:
        return text

    window = text[:hard_cap]
    for end in (". ", "! ", "? "):
        idx = window.find(end)
        if idx != -1:
            return window[: idx + 1].strip()

    cut = text.rfind(" ", 0, limit)
    if cut <= 0:
        cut = limit
    return text[:cut].rstrip() + "…"


def to_markdown(result: ScanResult) -> str:
    lines: list[str] = []
    lines.append(f"# Vulnerability report — {result.repo_name}")
    lines.append("")
    lines.append(f"- **Repository:** {result.repo_url}")
    if result.commit_sha:
        lines.append(f"- **Commit:** `{result.commit_sha[:12]}`")
    lines.append(f"- **Detected ecosystems:** {', '.join(result.detected_ecosystems) or 'none'}")
    lines.append(f"- **Duration:** {result.duration_seconds:.1f}s")
    lines.append(f"- **Total findings:** {result.total_findings}")
    lines.append(f"- **Security score:** {result.security_score}/100 (100 = no vulnerabilities)")
    lines.append("")

    lines.append("## Severity breakdown")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for severity in (
        Severity.CRITICAL,
        Severity.HIGH,
        Severity.MEDIUM,
        Severity.LOW,
        Severity.INFO,
        Severity.UNKNOWN,
    ):
        count = result.summary_by_severity.get(severity.value, 0)
        if count:
            lines.append(f"| {_SEVERITY_EMOJI[severity]} {severity.value.upper()} | {count} |")
    lines.append("")

    lines.append("## Scanners")
    lines.append("")
    lines.append("| Tool | Status | Findings | Duration |")
    lines.append("|---|---|---|---|")
    for run in result.scanner_runs:
        if run.ran:
            status = "✅ ran" if not run.error else f"⚠️ ran with error: {run.error}"
        elif not run.applicable:
            status = "⏭️ not applicable"
        else:
            status = f"⏭️ skipped — {run.skipped_reason}"
        lines.append(f"| {run.tool} | {status} | {run.finding_count} | {run.duration_seconds:.1f}s |")
    lines.append("")

    if result.total_findings == 0:
        lines.append("No findings with the scanners that ran. ")
        lines.append("If a scanner shows as 'skipped' above, install it to widen coverage.")
        lines.append("")
    else:
        lines.append("## Findings")
        lines.append("")
        for finding in result.sorted_findings():
            emoji = _SEVERITY_EMOJI.get(finding.severity, "⚪")
            location = f"`{finding.file_path}`" if finding.file_path else "(no specific file)"
            if finding.line:
                location += f":{finding.line}"

            lines.append(f"### {emoji} [{finding.severity.value.upper()}] {finding.title}")
            lines.append("")
            lines.append(f"- **Tool:** {finding.tool} (`{finding.rule_id}`)")
            lines.append(f"- **Location:** {location}")
            if finding.package_name:
                version_info = finding.installed_version or "?"
                lines.append(f"- **Package:** {finding.package_name}@{version_info}")
                if finding.fixed_version:
                    lines.append(f"- **Fixed in:** {finding.fixed_version}")
            if finding.cwe_ids:
                lines.append(f"- **CWE:** {', '.join(finding.cwe_ids)}")
            if finding.description:
                lines.append("")
                lines.append(_shorten(finding.description))
            if finding.remediation:
                lines.append("")
                lines.append(f"**Fix:** {finding.remediation}")
            lines.append("")

    lines.append("---")
    lines.append("_Generated by Elenk (open source)._")

    return "\n".join(lines)


def write_markdown_report(result: ScanResult, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(to_markdown(result), encoding="utf-8")
    return output_path
